"""
otalign
=======

Generated by Claude.

Self-contained implementation of **Gromov-Wasserstein alignment of word embedding
spaces** (Alvarez-Melis & Jaakkola, EMNLP 2018) for unsupervised bilingual lexicon
induction (BLI).

The problem
-----------
Given monolingual word embeddings for two languages and *no* seed dictionary,
recover word-to-word translations. Vectors from the two spaces are not directly
comparable -- there is no meaningful ``d(x_i, y_j)`` -- so ordinary optimal
transport does not apply. Gromov-Wasserstein (GW) instead compares each space's
*internal* geometry: it only needs the intra-domain distance matrices ``C1`` and
``C2``, and looks for a soft matching that makes the two relational structures
agree. Informally: *"dog" is to "cat" as "perro" is to "gato"*.

The pipeline
------------
1. Normalize both embedding matrices (:func:`normalize_vectors`).
2. Take the ``anchor_vocab`` most frequent words of each language and solve the
   entropic GW problem over them (:class:`GromovWassersteinAligner`), yielding a
   soft coupling ``T``.
3. Read mutual nearest neighbours out of ``T`` -- an automatically induced seed
   dictionary -- and fit an orthogonal map ``P`` by Procrustes
   (:func:`orthogonal_procrustes`).
4. Because ``P`` is ``d x d`` it applies to the *whole* vocabulary, so
   translations are available well beyond the words GW actually saw
   (:class:`Alignment`).

Nothing here is trained by gradient descent: there are no learned parameters.
The "model" is a coupling matrix obtained by constrained optimization plus an
orthogonal matrix obtained in closed form from an SVD. The input embeddings are
frozen throughout.

Quick start
-----------
::

    import otalign

    src = otalign.WordVectors.load("wiki.en.vec", max_vocab=200_000)
    trg = otalign.WordVectors.load("wiki.es.vec", max_vocab=200_000)

    alignment = otalign.align(src, trg, anchor_vocab=2000, maxiter=300)

    alignment.translate(["dog", "house"], k=5)
    # {'dog': ['perro', ...], 'house': ['casa', ...]}

    gold, _ = otalign.load_dictionary("en-es.0-5000.txt", src, trg)
    alignment.precision_at_k(gold)
    # {1: 0.63, 5: 0.79, 10: 0.83}

There is also a command line entry point; see ``python otalign.py --help``.

Dependencies
------------
``numpy`` and ``scipy`` only. The original code depended on POT (and, for the
GPU path, on ``cudamat``); the handful of primitives actually needed -- Sinkhorn,
the GW loss factorization, barycentric mapping -- are implemented directly here,
which removes the dependency churn that broke the original GPU path.

License: GPL v3.0 (inherited from the original implementation). Embedding text
I/O follows the format used by Artetxe's VecMap and Facebook's MUSE.
"""

from __future__ import annotations

import argparse
import collections
import os
import sys
import time
import warnings
from dataclasses import dataclass, field
from typing import Callable, Dict, Iterable, List, Optional, Sequence, Set, Tuple

import numpy as np
from scipy.spatial.distance import cdist

__all__ = [
    "WordVectors",
    "normalize_vectors",
    "GromovWassersteinAligner",
    "Alignment",
    "GWIterate",
    "align",
    "load_dictionary",
    "sinkhorn",
    "orthogonal_procrustes",
    "csls",
    "mutual_nearest_neighbors",
    "uniform_distribution",
    "zipf_distribution",
]

# Loss functions accepted by the GW solver.
SQUARE_LOSS = "square_loss"
KL_LOSS = "kl_loss"


# =============================================================================
# 1. Word vectors: I/O, containers, preprocessing
# =============================================================================


@dataclass
class WordVectors:
    """A vocabulary paired with its embedding matrix.

    Attributes
    ----------
    words:
        Vocabulary, in file order. Embedding files are conventionally sorted by
        descending corpus frequency, and the rest of this module relies on that:
        "the first ``k`` words" is taken to mean "the ``k`` most frequent words".
    vectors:
        Array of shape ``(len(words), dim)``. Row ``i`` is the vector of
        ``words[i]``.
    """

    words: List[str]
    vectors: np.ndarray

    def __post_init__(self) -> None:
        if len(self.words) != self.vectors.shape[0]:
            raise ValueError(
                f"vocabulary size ({len(self.words)}) does not match number of "
                f"vectors ({self.vectors.shape[0]})"
            )
        # First occurrence wins, matching the behaviour of the original loader.
        self._word2ind: Dict[str, int] = {}
        for i, w in enumerate(self.words):
            self._word2ind.setdefault(w, i)

    # -- basic container protocol -------------------------------------------

    def __len__(self) -> int:
        return len(self.words)

    def __repr__(self) -> str:
        return f"WordVectors(n={len(self)}, dim={self.dim})"

    @property
    def dim(self) -> int:
        """Embedding dimensionality."""
        return int(self.vectors.shape[1])

    @property
    def word2ind(self) -> Dict[str, int]:
        """Mapping from word to row index."""
        return self._word2ind

    def index(self, word: str) -> Optional[int]:
        """Row index of ``word``, or ``None`` if it is out of vocabulary."""
        return self._word2ind.get(word)

    def head(self, n: Optional[int]) -> "WordVectors":
        """The ``n`` most frequent words, as a new :class:`WordVectors`.

        Returns ``self`` unchanged when ``n`` is ``None`` or exceeds the
        vocabulary size. The returned object *views* the same underlying array,
        so it is cheap but is invalidated by in-place edits.
        """
        if n is None or n >= len(self):
            return self
        return WordVectors(self.words[:n], self.vectors[:n])

    # -- persistence ---------------------------------------------------------

    @classmethod
    def load(
        cls,
        path: str,
        max_vocab: Optional[int] = None,
        encoding: str = "utf-8",
        dtype: str = "float64",
    ) -> "WordVectors":
        """Read a whitespace-delimited embedding file.

        Accepts both the word2vec/fastText convention (a ``"<count> <dim>"``
        header line) and plain headerless files.

        Parameters
        ----------
        path:
            File to read.
        max_vocab:
            Read at most this many vectors. Since files are frequency-sorted
            this keeps the most frequent words. ``None`` reads everything.
        dtype:
            Storage dtype. ``float64`` matches the original implementation;
            ``float32`` halves memory at no practical cost in accuracy.
        """
        with open(path, encoding=encoding, errors="surrogateescape") as handle:
            first = handle.readline()
            header = _parse_header(first)

            if header is not None:
                count, dim = header
                n = count if max_vocab is None else min(max_vocab, count)
                words: List[str] = []
                matrix = np.empty((n, dim), dtype=dtype)
                for i in range(n):
                    line = handle.readline()
                    if not line:  # File is shorter than its header claims.
                        matrix = matrix[: len(words)]
                        break
                    word, vec = line.rstrip("\n").split(" ", 1)
                    words.append(word)
                    matrix[i] = np.fromstring(vec, sep=" ", dtype=dtype)
                return cls(words, matrix)

            # Headerless: the first line is already a vector.
            words, rows = [], []
            for line in _prepend(first, handle):
                if max_vocab is not None and len(words) >= max_vocab:
                    break
                stripped = line.rstrip("\n")
                if not stripped:
                    continue
                word, vec = stripped.split(" ", 1)
                words.append(word)
                rows.append(np.fromstring(vec, sep=" ", dtype=dtype))
            return cls(words, np.vstack(rows))

    def save(self, path: str, encoding: str = "utf-8") -> None:
        """Write the vectors back out in word2vec text format."""
        with open(path, "w", encoding=encoding, errors="surrogateescape") as handle:
            handle.write("%d %d\n" % self.vectors.shape)
            for word, vec in zip(self.words, self.vectors):
                handle.write(word + " " + " ".join("%.6g" % x for x in vec) + "\n")


def _parse_header(line: str) -> Optional[Tuple[int, int]]:
    """Return ``(count, dim)`` if ``line`` is a word2vec header, else ``None``."""
    parts = line.split()
    if len(parts) != 2:
        return None
    try:
        return int(parts[0]), int(parts[1])
    except ValueError:
        return None


def _prepend(first: str, rest: Iterable[str]) -> Iterable[str]:
    """Iterate ``first`` followed by ``rest`` (used to un-consume a read line)."""
    yield first
    for item in rest:
        yield item


def normalize_vectors(X: np.ndarray, method: str = "both") -> np.ndarray:
    """Preprocess an embedding matrix. Returns a new array; ``X`` is untouched.

    Preprocessing matters a great deal for GW, because the objective sees only
    the *intra*-domain distance matrices: any transformation that changes the
    shape of a space changes the problem.

    Parameters
    ----------
    method:
        - ``"mean"``      -- subtract the column mean (centering).
        - ``"both"``      -- centering, then scale each row to unit norm.
                             This is the default used in the paper.
        - ``"unit"``      -- unit-norm rows only, no centering.
        - ``"whiten"``    -- centering, then PCA whitening (identity covariance).
        - ``"whiten_zca"``-- centering, then ZCA whitening (identity covariance,
                             but staying as close to the original axes as
                             possible).
        - ``"none"``      -- return a copy unchanged.

    Notes
    -----
    Whitening is applied *once, over the whole vocabulary passed in*. Callers
    should therefore normalize the full embedding matrix before slicing out a
    subset, so that every vector ends up in the same frame -- see
    :meth:`GromovWassersteinAligner.fit`, which does exactly that.
    """
    X = np.asarray(X, dtype=np.float64)

    if method in (None, "none"):
        return X.copy()
    if method == "unit":
        return _unit_rows(X)
    if method == "mean":
        return X - X.mean(axis=0)
    if method == "both":
        return _unit_rows(X - X.mean(axis=0))
    if method in ("whiten", "whiten_zca"):
        centered = X - X.mean(axis=0)
        return _whiten(centered, zca=(method == "whiten_zca"))
    raise ValueError(f"unknown normalization method: {method!r}")


def _unit_rows(X: np.ndarray) -> np.ndarray:
    """Scale each row to unit L2 norm, leaving zero rows alone."""
    norms = np.linalg.norm(X, axis=1)
    norms[norms == 0] = 1.0
    return X / norms[:, None]


def _whiten(X: np.ndarray, zca: bool = False, eps: float = 1e-8) -> np.ndarray:
    """Whiten centered data so that the covariance becomes the identity.

    PCA whitening applies ``W = L^(-1/2) U'`` where ``Cov = U L U'``. ZCA
    additionally rotates back, ``W = U L^(-1/2) U'``, which keeps the whitened
    vectors as close as possible to the originals.

    ``eps`` regularizes the eigenvalues; without it, near-null directions -- of
    which word embeddings have plenty -- blow up.
    """
    cov = np.cov(X, rowvar=False)
    eigvals, eigvecs = np.linalg.eigh(cov)
    inv_sqrt = 1.0 / np.sqrt(np.maximum(eigvals, 0.0) + eps)
    # Rows of `W` are the whitening directions, so we right-multiply by W.T.
    W = (eigvecs * inv_sqrt) @ eigvecs.T if zca else (eigvecs * inv_sqrt).T
    return X @ W.T


# =============================================================================
# 2. Marginal distributions
# =============================================================================


def uniform_distribution(n: int) -> np.ndarray:
    """Uniform probability vector of length ``n``."""
    return np.full(n, 1.0 / n)


# Zipf-Mandelbrot shape parameters per language, from Piantadosi (2014).
_ZIPF_PARAMS: Dict[str, Tuple[float, float]] = {
    "en": (1.40, 1.88),
    "fi": (1.17, 0.60),
    "fr": (1.71, 2.09),
    "de": (1.10, 0.40),
    "es": (1.84, 3.81),
}
_ZIPF_DEFAULT = _ZIPF_PARAMS["en"]


def zipf_distribution(n: int, lang: str = "en") -> np.ndarray:
    """Zipf-Mandelbrot mass over a frequency-sorted vocabulary of size ``n``.

    ``p_i ~ 1 / (i + beta)^alpha``. Unlike the uniform marginal this encodes the
    prior that rank ``i`` in one language should carry comparable mass to rank
    ``i`` in the other. Unknown languages fall back to the English parameters.
    """
    alpha, beta = _ZIPF_PARAMS.get(lang, _ZIPF_DEFAULT)
    p = np.array([1.0 / ((i + 1) + beta) ** alpha for i in range(n)])
    return p / p.sum()


def _marginal(kind: str, n: int, lang: str) -> np.ndarray:
    """Build a marginal by name (``"uniform"`` or ``"zipf"``)."""
    if kind == "uniform":
        return uniform_distribution(n)
    if kind == "zipf":
        return zipf_distribution(n, lang)
    raise ValueError(f"unknown marginal distribution: {kind!r}")


# =============================================================================
# 3. Entropic optimal transport (Sinkhorn)
# =============================================================================


@dataclass
class SinkhornState:
    """Scaling vectors carried between successive Sinkhorn solves (warm start).

    ``u`` and ``v`` are the multiplicative scalings such that the transport plan
    is ``diag(u) K diag(v)``. ``shift`` records the constant that was subtracted
    from the cost matrix when ``K`` was built, which is needed to reinterpret
    ``u``/``v`` against a differently shifted cost -- see :func:`sinkhorn`.
    """

    u: np.ndarray
    v: np.ndarray
    shift: float


def sinkhorn(
    a: np.ndarray,
    b: np.ndarray,
    M: np.ndarray,
    reg: float,
    warm_start: Optional[SinkhornState] = None,
    numItermax: int = 1000,
    stopThr: float = 1e-9,
    check_every: int = 10,
) -> Tuple[np.ndarray, SinkhornState, int, bool]:
    r"""Solve the entropy-regularized optimal transport problem.

    .. math::
        \min_T \langle T, M \rangle + \mathrm{reg} \sum_{ij} T_{ij}\log T_{ij}
        \quad\text{s.t.}\quad T\mathbf{1}=a,\; T^\top\mathbf{1}=b,\; T\ge 0

    via Sinkhorn-Knopp matrix scaling (Cuturi, 2013).

    Parameters
    ----------
    a, b:
        Source and target marginals, each summing to 1.
    M:
        Cost matrix of shape ``(len(a), len(b))``.
    reg:
        Entropic regularization strength. Smaller values give sharper, more
        permutation-like plans but are numerically harder.
    stopThr:
        Stopping threshold on the *squared* L2 error of the target marginal,
        ``||T^T 1 - b||^2``. Squared, and checked every ``check_every``
        iterations, to match the original implementation and POT so that
        published tolerances carry over unchanged. Note the asymmetry: the loop
        ends on the ``u`` update, so ``T 1 == a`` holds to machine precision
        while ``T^T 1 == b`` holds only to roughly ``sqrt(stopThr)``.
    warm_start:
        Scalings from a previous solve. Reusing them across outer GW iterations
        cuts the inner iteration count substantially, since the cost matrix
        changes only a little from one outer step to the next.

    Returns
    -------
    T:
        The transport plan.
    state:
        Scalings to feed back in as the next ``warm_start``.
    n_iter:
        Inner iterations performed.
    converged:
        ``False`` if the loop hit ``numItermax`` or bailed out on a numerical
        breakdown, in which case ``T`` is the last usable iterate.

    Notes
    -----
    **Numerical stabilization.** The kernel ``K = exp(-M/reg)`` underflows to
    zero whenever ``min(M)/reg`` exceeds ~745, which at the default
    ``reg = 5e-4`` happens for essentially every GW gradient. Subtracting a
    constant from ``M`` leaves the optimal plan unchanged (it rescales ``u`` and
    ``v`` by reciprocal factors), so we always shift by ``M.min()``. This is the
    main difference from the original implementation, which had no shift and
    reported "numerical errors" instead.

    Because the shift differs from call to call, a warm start computed under a
    previous shift must be rescaled by ``exp(-(c_new - c_old) / (2 reg))``,
    split evenly between ``u`` and ``v`` to halve the exponent. If that factor
    would itself overflow, we silently fall back to a cold start.
    """
    a = np.asarray(a, dtype=np.float64)
    b = np.asarray(b, dtype=np.float64)
    M = np.asarray(M, dtype=np.float64)

    # Shift the cost so the cheapest pair has cost 0; see the note above.
    shift = float(M.min())
    K = np.exp(-(M - shift) / reg)
    Kp = K / a[:, None]  # Precomputed for the u update.

    u, v = _init_scalings(a, b, warm_start, shift, reg)

    n_iter, err, converged = 0, np.inf, False
    while n_iter < numItermax:
        u_prev, v_prev = u, v

        KTu = K.T @ u
        v = b / KTu
        u = 1.0 / (Kp @ v)

        if not (np.all(np.isfinite(u)) and np.all(np.isfinite(v))):
            # Machine precision exhausted: keep the last good iterate.
            u, v = u_prev, v_prev
            break

        n_iter += 1
        if n_iter % check_every == 0:
            # Marginal violation on the target side; the source side is exact
            # by construction of the u update.
            marginal = (u[:, None] * K * v[None, :]).sum(axis=0)
            err = float(np.linalg.norm(marginal - b) ** 2)
            if err < stopThr:
                converged = True
                break

    T = u[:, None] * K * v[None, :]
    return T, SinkhornState(u, v, shift), n_iter, converged


def _init_scalings(
    a: np.ndarray,
    b: np.ndarray,
    warm_start: Optional[SinkhornState],
    shift: float,
    reg: float,
) -> Tuple[np.ndarray, np.ndarray]:
    """Produce the initial ``(u, v)``, rescaling a warm start if usable."""
    cold = (np.full(len(a), 1.0 / len(a)), np.full(len(b), 1.0 / len(b)))
    if warm_start is None:
        return cold

    # Correct for the change in cost shift; see the note in `sinkhorn`.
    exponent = -(shift - warm_start.shift) / (2.0 * reg)
    if abs(exponent) > 700.0:  # exp() would overflow/underflow float64
        return cold
    scale = np.exp(exponent)
    u, v = warm_start.u * scale, warm_start.v * scale
    if not (np.all(np.isfinite(u)) and np.all(np.isfinite(v))):
        return cold
    return u, v


# =============================================================================
# 4. Gromov-Wasserstein solver
# =============================================================================


def _loss_factorization(
    C1: np.ndarray,
    C2: np.ndarray,
    p: np.ndarray,
    q: np.ndarray,
    loss: str,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    r"""Precompute the terms that make the GW gradient cheap.

    Evaluated naively, the GW objective is a sum over four indices and costs
    ``O(n^2 m^2)``. Peyre et al. (ICML 2016), Proposition 1, observe that for
    losses decomposable as ``L(x, y) = f1(x) + f2(y) - h1(x) h2(y)`` the tensor
    contraction reduces to

    .. math:: \mathcal{L}(C_1, C_2) \otimes T = \mathrm{constC} - h_1(C_1)\, T\, h_2(C_2)^\top

    which is a pair of matrix products, ``O(n^2 m + n m^2)``.

    - ``square_loss``: ``f1(x)=x^2/2``, ``f2(y)=y^2/2``, ``h1(x)=x``, ``h2(y)=y``
    - ``kl_loss``:     ``f1(x)=x log x - x``, ``f2(y)=y``, ``h1(x)=x``,
      ``h2(y)=log y`` (requires non-negative cost matrices)

    Returns ``(constC, hC1, hC2)``, all independent of ``T``.
    """
    if loss == SQUARE_LOSS:
        f1, f2 = lambda x: (x ** 2) / 2.0, lambda y: (y ** 2) / 2.0
        h1, h2 = lambda x: x, lambda y: y
    elif loss == KL_LOSS:
        f1, f2 = lambda x: x * np.log(x + 1e-15) - x, lambda y: y
        h1, h2 = lambda x: x, lambda y: np.log(y + 1e-15)
    else:
        raise ValueError(f"unknown loss function: {loss!r}")

    # constC_ij = sum_k f1(C1_ik) p_k + sum_l f2(C2_jl) q_l  -- rank-1 in each term.
    constC = (f1(C1) @ p)[:, None] + (f2(C2) @ q)[None, :]
    return constC, h1(C1), h2(C2)


def _gw_tensor(constC: np.ndarray, hC1: np.ndarray, hC2: np.ndarray, T: np.ndarray) -> np.ndarray:
    """The factorized tensor-matrix product ``L(C1, C2) (x) T``."""
    return constC - hC1 @ T @ hC2.T


def _gw_loss(constC: np.ndarray, hC1: np.ndarray, hC2: np.ndarray, T: np.ndarray) -> float:
    """GW objective value at ``T`` (excluding the entropic term)."""
    return float(np.sum(_gw_tensor(constC, hC1, hC2, T) * T))


def _gw_gradient(constC: np.ndarray, hC1: np.ndarray, hC2: np.ndarray, T: np.ndarray) -> np.ndarray:
    """Gradient of the GW objective at ``T``. Acts as a linear OT cost matrix."""
    return 2.0 * _gw_tensor(constC, hC1, hC2, T)


def _pairwise_distances(X: np.ndarray, metric: str, normalize: str) -> np.ndarray:
    """Intra-domain distance matrix, rescaled so the two languages are comparable.

    The rescaling is essential: GW compares distances across spaces, and the raw
    scales of two independently trained embedding spaces are arbitrary.
    """
    C = _cosine_distances(X) if metric == "cosine" else cdist(X, X, metric=metric)
    if normalize in (None, "none"):
        return C
    if normalize == "mean":
        return C / C.mean()
    if normalize == "max":
        return C / C.max()
    if normalize == "median":
        return C / np.median(C)
    raise ValueError(f"unknown distance normalization: {normalize!r}")


def _cosine_distances(X: np.ndarray) -> np.ndarray:
    """Self-distance matrix under the cosine metric, computed as one GEMM.

    ``cdist(X, X, metric="cosine")`` evaluates the dot product of every pair in
    a scalar, single-threaded C loop. Since cosine distance is
    ``1 - <x, y> / (||x|| ||y||)``, unit-normalizing the rows first reduces the
    whole matrix to ``1 - Xn @ Xn.T`` -- a single BLAS call, which is both
    blocked for cache and multi-threaded. Same values, orders of magnitude
    faster; the O(n*d) normalization is negligible beside the O(n^2 d) product.

    One deliberate difference from ``cdist``: a zero row has no direction, and
    ``cdist`` reports its distances as ``nan``. Here :func:`_unit_rows` leaves
    it at zero, so it sits at distance 1 from everything. That keeps a single
    degenerate vector from poisoning the entire GW objective with ``nan``.
    """
    Xn = _unit_rows(np.asarray(X, dtype=np.float64))
    C = 1.0 - Xn @ Xn.T
    # Rounding can put entries a few ulp outside the true range of the metric,
    # and leaves ~1e-16 rather than 0 on the diagonal. Both matter: `kl_loss`
    # takes the log of these, and the diagonal is what fixes the loss's scale.
    np.clip(C, 0.0, 2.0, out=C)
    np.fill_diagonal(C, 0.0)
    return C


@dataclass
class GWIterate:
    """Diagnostics recorded at one outer iteration of the GW solver."""

    iteration: int
    gw_distance: float
    entropy: float
    delta: float  #: Frobenius norm of the change in the coupling
    sinkhorn_iters: int
    elapsed: float  #: Seconds since the start of the solve


class GromovWassersteinAligner:
    """Aligns two embedding spaces by solving an entropic Gromov-Wasserstein problem.

    The objective is

    .. math::
        \\min_T \\sum_{ijkl} L(C1_{ik}, C2_{jl}) T_{ij} T_{kl} - \\epsilon H(T)
        \\quad\\text{s.t.}\\quad T\\mathbf{1}=p,\\ T^\\top\\mathbf{1}=q,\\ T\\ge 0

    a *non-convex* quadratic program. It is solved by projected gradient: at each
    outer step the objective is linearized at the current ``T`` and the resulting
    entropic OT problem is solved by Sinkhorn. This converges to a stationary
    point, not a global optimum, so results depend on preprocessing and on
    ``entreg``.

    Parameters
    ----------
    anchor_vocab:
        Number of most-frequent words per language to include in the GW problem.
        Cost is quadratic in this number (see :meth:`fit`), so it is normally
        kept in the low thousands; the orthogonal map fitted afterwards is what
        extends coverage to the full vocabulary.
    metric:
        Distance used for the intra-domain matrices: ``"cosine"`` (default),
        ``"euclidean"`` or ``"sqeuclidean"``.
    normalize_vecs:
        Embedding preprocessing; see :func:`normalize_vectors`.
    normalize_dists:
        Rescaling applied to each distance matrix: ``"mean"`` (default),
        ``"max"``, ``"median"`` or ``"none"``.
    loss:
        ``"square_loss"`` (default) or ``"kl_loss"``.
    entreg:
        Entropic regularization ``epsilon``; the default of ``5e-4`` is the
        paper's. **This is the parameter most worth watching.** The independence
        coupling used to initialize the solve is itself very nearly a stationary
        point, and if ``entreg`` is too large for the problem the first Sinkhorn
        step returns something indistinguishable from it: the run "converges"
        immediately to a uniform coupling that encodes nothing. The symptom is a
        solve that stops after a couple of iterations with an entropy of about
        ``log(n*m) + 1``, followed by a warning about too few anchors. The safe
        direction is *smaller*. The usable ceiling falls as ``anchor_vocab``
        grows -- at 800 anchors, ``1e-3`` still works and ``5e-3`` does not.
    tol:
        Outer stopping threshold on ``||T - T_prev||_F``.
    maxiter:
        Maximum outer iterations.
    sinkhorn_maxiter, sinkhorn_tol:
        Inner Sinkhorn budget and tolerance.
    warm_start:
        Reuse Sinkhorn scalings across outer iterations. Usually a large speedup;
        disable it if you suspect it is hurting inner convergence.
    distribs:
        Marginals over each vocabulary: ``"uniform"`` (default) or ``"zipf"``.
    anchor_method:
        How to pick the pseudo-dictionary used to fit the orthogonal map:
        ``"mutual_nn"`` (default; pairs that are each other's best match --
        high precision, and the choice used in the paper) or ``"all"`` (every
        source word's top-1 target, higher recall but noisier).
    max_anchors:
        Cap on the number of anchor pairs, or ``None`` for all of them.
    verbose:
        Print a progress table.
    callback:
        Optional ``fn(GWIterate, T) -> None`` invoked every ``log_every``
        iterations. Useful for tracking downstream accuracy during the solve.
    """

    def __init__(
        self,
        anchor_vocab: int = 2000,
        metric: str = "cosine",
        normalize_vecs: str = "both",
        normalize_dists: str = "mean",
        loss: str = SQUARE_LOSS,
        entreg: float = 5e-4,
        tol: float = 1e-9,
        maxiter: int = 300,
        sinkhorn_maxiter: int = 1000,
        sinkhorn_tol: float = 1e-9,
        warm_start: bool = True,
        distribs: str = "uniform",
        anchor_method: str = "mutual_nn",
        max_anchors: Optional[int] = None,
        verbose: bool = True,
        log_every: int = 10,
        callback: Optional[Callable[[GWIterate, np.ndarray], None]] = None,
    ) -> None:
        self.anchor_vocab = anchor_vocab
        self.metric = metric
        self.normalize_vecs = normalize_vecs
        self.normalize_dists = normalize_dists
        self.loss = loss
        self.entreg = entreg
        self.tol = tol
        self.maxiter = maxiter
        self.sinkhorn_maxiter = sinkhorn_maxiter
        self.sinkhorn_tol = sinkhorn_tol
        self.warm_start = warm_start
        self.distribs = distribs
        self.anchor_method = anchor_method
        self.max_anchors = max_anchors
        self.verbose = verbose
        self.log_every = log_every
        self.callback = callback

        self.history: List[GWIterate] = []

    # -- main entry point ----------------------------------------------------

    def fit(
        self,
        src: WordVectors,
        trg: WordVectors,
        src_lang: str = "src",
        trg_lang: str = "trg",
    ) -> "Alignment":
        """Align two embedding spaces and return the resulting :class:`Alignment`.

        Both vocabularies are normalized in full first, then the first
        ``anchor_vocab`` rows of each are used for the GW problem. Normalizing
        before slicing keeps every vector -- including those GW never sees -- in
        the same frame, which is what makes the fitted orthogonal map valid over
        the whole vocabulary.

        ``src_lang`` / ``trg_lang`` are ISO codes used only to select
        Zipf parameters (when ``distribs="zipf"``) and to label output files.

        Cost
        ----
        With ``n = m = anchor_vocab``, memory is ``O(n^2)`` for each distance
        matrix -- at ``n = 20000`` that pair alone is ~6.4 GB in float64 -- and
        each outer iteration costs ``O(n^3)`` for the gradient plus ``O(n^2)``
        per inner Sinkhorn step.
        """
        src_norm = WordVectors(src.words, normalize_vectors(src.vectors, self.normalize_vecs))
        trg_norm = WordVectors(trg.words, normalize_vectors(trg.vectors, self.normalize_vecs))

        src_anchor = src_norm.head(self.anchor_vocab)
        trg_anchor = trg_norm.head(self.anchor_vocab)
        n, m = len(src_anchor), len(trg_anchor)

        if self.verbose:
            print(f"Solving GW over {n} x {m} words (dim {src_norm.dim}).")

        p = _marginal(self.distribs, n, src_lang)
        q = _marginal(self.distribs, m, trg_lang)

        coupling = self.solve(src_anchor.vectors, trg_anchor.vectors, p, q)

        alignment = Alignment(
            coupling=coupling,
            mapping=np.eye(src_norm.dim),
            src=src_norm,
            trg=trg_norm,
            src_lang=src_lang,
            trg_lang=trg_lang,
            history=list(self.history),
            metric=self.metric,
        )
        alignment.mapping = alignment.fit_mapping(
            anchor_method=self.anchor_method,
            max_anchors=self.max_anchors,
            verbose=self.verbose,
        )
        return alignment

    def solve(
        self,
        xs: np.ndarray,
        xt: np.ndarray,
        p: Optional[np.ndarray] = None,
        q: Optional[np.ndarray] = None,
    ) -> np.ndarray:
        """Run the GW iteration on raw matrices and return the coupling.

        Lower-level than :meth:`fit`: takes vectors that are *already*
        normalized, applies no post-processing, and returns just ``T``. Useful
        for aligning point clouds that are not word embeddings.
        """
        n, m = xs.shape[0], xt.shape[0]
        p = uniform_distribution(n) if p is None else np.asarray(p, dtype=np.float64)
        q = uniform_distribution(m) if q is None else np.asarray(q, dtype=np.float64)

        if self.verbose:
            print("Computing intra-domain distance matrices...")
        C1 = _pairwise_distances(xs, self.metric, self.normalize_dists)
        C2 = _pairwise_distances(xt, self.metric, self.normalize_dists)

        constC, hC1, hC2 = _loss_factorization(C1, C2, p, q, self.loss)

        T = np.outer(p, q)  # Independence coupling: the least committed start.
        state: Optional[SinkhornState] = None
        self.history = []
        started = time.time()

        if self.verbose:
            self._print_header()

        for it in range(self.maxiter + 1):
            T_prev = T
            gradient = _gw_gradient(constC, hC1, hC2, T)
            T, state, inner_iters, _ = sinkhorn(
                p,
                q,
                gradient,
                self.entreg,
                warm_start=state if self.warm_start else None,
                numItermax=self.sinkhorn_maxiter,
                stopThr=self.sinkhorn_tol,
            )

            delta = float(np.linalg.norm(T - T_prev))
            should_log = (it % self.log_every == 0) or delta <= self.tol

            if should_log or self.callback is not None:
                record = GWIterate(
                    iteration=it,
                    gw_distance=_gw_loss(constC, hC1, hC2, T),
                    entropy=_coupling_entropy(T),
                    delta=delta,
                    sinkhorn_iters=inner_iters,
                    elapsed=time.time() - started,
                )
                self.history.append(record)
                if self.verbose and should_log:
                    self._print_row(record)
                if self.callback is not None:
                    self.callback(record, T)

            if delta <= self.tol:
                if self.verbose:
                    print(f"Converged at iteration {it} (delta={delta:.2e}).")
                break
        else:
            if self.verbose:
                print(f"Stopped at maxiter={self.maxiter} (delta={delta:.2e}).")

        return T

    # -- progress reporting --------------------------------------------------

    @staticmethod
    def _print_header() -> None:
        head = "{:>6} {:>12} {:>12} {:>12} {:>8} {:>9}".format(
            "iter", "gw_dist", "entropy", "delta", "sink_it", "time(s)"
        )
        print("-" * len(head))
        print(head)
        print("-" * len(head))

    @staticmethod
    def _print_row(r: GWIterate) -> None:
        print(
            "{:6d} {:12.4e} {:12.4e} {:12.4e} {:8d} {:9.2f}".format(
                r.iteration, r.gw_distance, r.entropy, r.delta,
                r.sinkhorn_iters, r.elapsed,
            )
        )


def _coupling_entropy(T: np.ndarray) -> float:
    """Entropy ``-sum T (log T - 1)`` of a coupling, ignoring zero entries.

    This is the term the entropic regularizer maximizes. It rises as the plan
    blurs and falls as it sharpens toward a permutation, which makes it a useful
    read on whether ``entreg`` is set sensibly.
    """
    with np.errstate(divide="ignore", invalid="ignore"):
        terms = T * (np.log(T) - 1.0)
    return float(-np.nan_to_num(terms).sum())


# =============================================================================
# 5. From coupling to translations
# =============================================================================


def orthogonal_procrustes(X: np.ndarray, Y: np.ndarray) -> np.ndarray:
    r"""Solve :math:`\min_P \|X - Y P^\top\|_F` subject to :math:`P^\top P = I`.

    Closed form: with :math:`X^\top Y = U \Sigma V^\top`, the optimum is
    :math:`P = U V^\top`.

    Rows are observations (the ML convention), not columns. With ``X`` a block
    of source vectors and ``Y`` the corresponding target vectors, the returned
    ``P`` maps *target into source* space as ``Y @ P.T``.
    """
    U, _, Vt = np.linalg.svd(X.T @ Y)
    return U @ Vt


def mutual_nearest_neighbors(scores: np.ndarray) -> List[Tuple[int, int]]:
    """Index pairs ``(i, j)`` that are each other's highest-scoring match.

    Mutual agreement is a strong precision filter: it discards source words whose
    best target already prefers someone else, which is exactly the failure mode
    of hub words. The survivors serve as a seed dictionary that was never
    supervised.
    """
    best_for_src = scores.argmax(axis=1)
    best_for_trg = scores.argmax(axis=0)
    return [(i, int(j)) for i, j in enumerate(best_for_src) if best_for_trg[j] == i]


def _mean_topk(scores: np.ndarray, knn: int, axis: int) -> np.ndarray:
    """Mean of the ``knn`` largest values along ``axis``.

    ``axis=1`` gives, for each row, its mean similarity to its ``knn`` best
    columns; ``axis=0`` does the same per column.
    """
    S = scores if axis == 1 else scores.T
    knn = min(knn, S.shape[1])
    idx = np.argpartition(S, -knn, axis=1)[:, -knn:]
    return np.take_along_axis(S, idx, axis=1).mean(axis=1)


def csls(scores: np.ndarray, knn: int = 10) -> np.ndarray:
    """Cross-domain Similarity Local Scaling (Conneau et al., 2018).

    ``csls(x, y) = 2 s(x, y) - r_s(x) - r_t(y)``, where each ``r`` is the mean
    similarity to the ``knn`` nearest neighbours in the other space.

    This corrects for *hubness*: in high dimensions a few vectors sit close to
    very many others and win nearest-neighbour queries they have no business
    winning. Penalizing each point by its own neighbourhood density removes the
    advantage. Costs ``O(nm)`` memory, since it needs the whole score matrix.
    """
    r_s = _mean_topk(scores, knn, axis=1)
    r_t = _mean_topk(scores, knn, axis=0)
    return 2.0 * scores - r_s[:, None] - r_t[None, :]


@dataclass
class Alignment:
    """The fitted alignment between two embedding spaces.

    Attributes
    ----------
    coupling:
        Soft matching ``T`` of shape ``(n_anchor_src, n_anchor_trg)``, defined
        only over the words GW actually optimized over.
    mapping:
        Orthogonal ``P`` of shape ``(dim, dim)``. Maps target into source space
        as ``xt @ P.T``, and therefore applies to the *entire* vocabulary.
    src, trg:
        The full, normalized vocabularies.
    history:
        Per-iteration solver diagnostics.
    """

    coupling: np.ndarray
    mapping: np.ndarray
    src: WordVectors
    trg: WordVectors
    src_lang: str = "src"
    trg_lang: str = "trg"
    history: List[GWIterate] = field(default_factory=list)

    #: Default retrieval scoring; see :meth:`score_matrix`.
    score_type: str = "projected"
    #: Default neighbourhood correction: ``"csls"`` or ``None``.
    adjust: Optional[str] = "csls"
    #: Metric for distance-based scoring. Cosine by default, matching the
    #: default used for the GW distance matrices.
    metric: str = "cosine"

    @property
    def n_anchor_src(self) -> int:
        """Number of source words covered by :attr:`coupling`."""
        return int(self.coupling.shape[0])

    @property
    def n_anchor_trg(self) -> int:
        """Number of target words covered by :attr:`coupling`."""
        return int(self.coupling.shape[1])

    # -- fitting the linear map ---------------------------------------------

    def fit_mapping(
        self,
        anchor_method: str = "mutual_nn",
        max_anchors: Optional[int] = None,
        verbose: bool = False,
    ) -> np.ndarray:
        """Fit the orthogonal map from anchor pairs read out of the coupling.

        This is the step that turns a coupling over a few thousand words into
        something usable over the whole vocabulary. See
        :func:`mutual_nearest_neighbors` and :func:`orthogonal_procrustes`.
        """
        scores = self.coupling
        if anchor_method == "mutual_nn":
            pairs = mutual_nearest_neighbors(scores)
        elif anchor_method == "all":
            pairs = [(i, int(j)) for i, j in enumerate(scores.argmax(axis=1))]
        else:
            raise ValueError(f"unknown anchor method: {anchor_method!r}")

        dim = self.src.dim
        if len(pairs) < dim:
            # Fewer anchors than dimensions leaves the Procrustes fit
            # underdetermined: the SVD still returns an orthogonal matrix, but
            # it is arbitrary on the unconstrained subspace, so the map would be
            # silently meaningless.
            message = (
                f"only {len(pairs)} anchor pairs for a {dim}-dimensional map. "
                "The coupling is close to degenerate -- most often because "
                "`entreg` is too large for this `anchor_vocab`, leaving the "
                "solver at the independence coupling it started from. Try "
                "lowering `entreg` (5e-4 is the paper's default), raising "
                "`maxiter`, or a different `normalize_vecs`."
            )
            if not pairs:
                raise RuntimeError(message)
            warnings.warn(message, RuntimeWarning, stacklevel=2)

        if max_anchors:
            pairs = pairs[:max_anchors]
        if verbose:
            print(f"Fitting orthogonal map from {len(pairs)} anchors ({anchor_method}).")

        idx_src = [i for i, _ in pairs]
        idx_trg = [j for _, j in pairs]
        return orthogonal_procrustes(self.src.vectors[idx_src], self.trg.vectors[idx_trg])

    # -- scoring -------------------------------------------------------------

    def score_matrix(
        self,
        score_type: Optional[str] = None,
        adjust: Optional[str] = "__default__",
        n_src: Optional[int] = None,
        n_trg: Optional[int] = None,
        csls_knn: int = 10,
    ) -> np.ndarray:
        """Translation scores (higher is better) for a slice of the vocabularies.

        Parameters
        ----------
        score_type:
            - ``"coupling"``    -- the GW coupling itself. Restricted to the
              anchor words; the sharpest signal where it is defined.
            - ``"projected"``   -- negative distance after applying ``P``.
              Defined over the whole vocabulary. The default.
            - ``"barycentric"`` -- map each target word to the coupling-weighted
              average of its source matches, then measure distance there.
              Restricted to the anchor words.
        adjust:
            ``"csls"`` or ``None``. Defaults to :attr:`adjust`.
        n_src, n_trg:
            Restrict to the first N words of each vocabulary. Required in
            practice for ``"projected"`` -- the full matrix is ``|V_s| x |V_t|``,
            which for two 200k vocabularies is 320 GB.

        Notes
        -----
        Memory is ``O(n_src * n_trg)``, and CSLS needs the matrix materialized,
        so cap both when working beyond the anchor set.
        """
        score_type = score_type or self.score_type
        adjust = self.adjust if adjust == "__default__" else adjust

        if score_type == "coupling":
            scores = self._slice_anchor(self.coupling, score_type, n_src, n_trg)
        elif score_type == "barycentric":
            scores = self._slice_anchor(self._barycentric_scores(), score_type, n_src, n_trg)
        elif score_type == "projected":
            xs = self.src.vectors[: n_src or len(self.src)]
            xt = self.trg.vectors[: n_trg or len(self.trg)]
            scores = -cdist(xs, xt @ self.mapping.T, metric=self.metric)
        else:
            raise ValueError(f"unknown score type: {score_type!r}")

        if adjust == "csls":
            scores = csls(scores, knn=csls_knn)
        elif adjust not in (None, "none"):
            raise ValueError(f"unknown score adjustment: {adjust!r}")
        return scores

    def _slice_anchor(
        self, scores: np.ndarray, score_type: str, n_src: Optional[int], n_trg: Optional[int]
    ) -> np.ndarray:
        """Clip an anchor-only score matrix, rejecting out-of-range requests."""
        if (n_src or 0) > scores.shape[0] or (n_trg or 0) > scores.shape[1]:
            raise ValueError(
                f"score_type={score_type!r} is only defined over the "
                f"{scores.shape[0]}x{scores.shape[1]} anchor vocabulary; use "
                f"score_type='projected' for the full vocabulary."
            )
        return scores[: n_src or scores.shape[0], : n_trg or scores.shape[1]]

    def _barycentric_scores(self) -> np.ndarray:
        """Score anchors by distance after barycentric projection of the target.

        Each target word is replaced by the coupling-weighted mean of the source
        words it is matched to, which places both languages in the source space
        without ever fitting a linear map.
        """
        weights = self.coupling.T / self.coupling.sum(axis=0)[:, None]
        trg_in_src = np.nan_to_num(weights) @ self.src.vectors[: self.n_anchor_src]
        return -cdist(self.src.vectors[: self.n_anchor_src], trg_in_src, metric=self.metric)

    # -- retrieval -----------------------------------------------------------

    def translate(
        self,
        words: Sequence[str],
        k: int = 1,
        score_type: Optional[str] = None,
        adjust: Optional[str] = "__default__",
        n_trg: Optional[int] = 50_000,
        csls_knn: int = 10,
    ) -> Dict[str, List[str]]:
        """Return the top-``k`` translation candidates for each of ``words``.

        Out-of-vocabulary queries are omitted from the result rather than raising.

        ``n_trg`` caps the candidate pool to the most frequent target words,
        which bounds both memory and the damage a rare-word hub can do. Pass
        ``None`` to search the entire target vocabulary.
        """
        score_type = score_type or self.score_type
        adjust = self.adjust if adjust == "__default__" else adjust

        indices, present = [], []
        for word in words:
            idx = self.src.index(word)
            if idx is not None:
                indices.append(idx)
                present.append(word)
        if not indices:
            return {}

        n_src = max(indices) + 1
        scores = self.score_matrix(
            score_type=score_type, adjust=adjust, n_src=n_src, n_trg=n_trg, csls_knn=csls_knn
        )
        return {
            word: [self.trg.words[j] for j in _topk(scores[idx], k)]
            for word, idx in zip(present, indices)
        }

    def precision_at_k(
        self,
        gold: Dict[int, Set[int]],
        ks: Sequence[int] = (1, 5, 10),
        score_type: Optional[str] = None,
        adjust: Optional[str] = "__default__",
        n_trg: Optional[int] = 50_000,
        csls_knn: int = 10,
        verbose: bool = False,
    ) -> Dict[int, float]:
        """Precision@k against a gold dictionary of *index* pairs.

        ``gold`` maps a source row index to the set of acceptable target row
        indices, as returned by :func:`load_dictionary`.

        The denominator is the full size of ``gold``: source words that fall
        outside the scored slice count as errors rather than being dropped. That
        matches the original implementation and keeps numbers comparable to
        published results, but it means a small ``n_trg`` depresses the score
        rather than silently shrinking the test set.
        """
        score_type = score_type or self.score_type
        adjust = self.adjust if adjust == "__default__" else adjust
        if not gold:
            raise ValueError("gold dictionary is empty")

        n_src = max(gold) + 1
        scores = self.score_matrix(
            score_type=score_type, adjust=adjust, n_src=n_src, n_trg=n_trg, csls_knn=csls_knn
        )
        n_scored_src, n_scored_trg = scores.shape

        correct = {k: 0 for k in ks}
        evaluable = 0
        for src_idx, trg_idxs in gold.items():
            in_range = [j for j in trg_idxs if j < n_scored_trg]
            if src_idx >= n_scored_src or not in_range:
                continue  # Counts against the denominator; see the docstring.
            evaluable += 1
            ranking = _topk(scores[src_idx], max(ks))
            for k in ks:
                if set(ranking[:k]) & set(in_range):
                    correct[k] += 1

        precisions = {k: correct[k] / len(gold) for k in ks}
        if verbose:
            coverage = evaluable / len(gold)
            print(
                "coverage: {:6.2%}   ".format(coverage)
                + "   ".join("P@{}: {:6.2%}".format(k, v) for k, v in precisions.items())
            )
        return precisions

    # -- exporting -----------------------------------------------------------

    def project_target(self) -> WordVectors:
        """The full target vocabulary mapped into the source space (``xt @ P.T``)."""
        return WordVectors(self.trg.words, self.trg.vectors @ self.mapping.T)

    def export(self, outdir: str) -> None:
        """Write both vocabularies into a shared space, plus the fitted arrays.

        Produces ``vectors-<src_lang>.txt`` (unchanged source),
        ``vectors-<trg_lang>.txt`` (target projected into the source space) and
        ``alignment.npz``.
        """
        os.makedirs(outdir, exist_ok=True)
        self.src.save(os.path.join(outdir, f"vectors-{self.src_lang}.txt"))
        self.project_target().save(os.path.join(outdir, f"vectors-{self.trg_lang}.txt"))
        self.save(os.path.join(outdir, "alignment.npz"))

    def save(self, path: str) -> None:
        """Persist the coupling, the mapping and both vocabularies to an ``.npz``."""
        np.savez_compressed(
            path,
            coupling=self.coupling,
            mapping=self.mapping,
            src_vectors=self.src.vectors,
            trg_vectors=self.trg.vectors,
            src_words=np.array(self.src.words, dtype=object),
            trg_words=np.array(self.trg.words, dtype=object),
            langs=np.array([self.src_lang, self.trg_lang], dtype=object),
        )

    @classmethod
    def load(cls, path: str) -> "Alignment":
        """Reload an alignment written by :meth:`save`."""
        data = np.load(path, allow_pickle=True)
        langs = data["langs"]
        return cls(
            coupling=data["coupling"],
            mapping=data["mapping"],
            src=WordVectors(list(data["src_words"]), data["src_vectors"]),
            trg=WordVectors(list(data["trg_words"]), data["trg_vectors"]),
            src_lang=str(langs[0]),
            trg_lang=str(langs[1]),
        )


def _topk(row: np.ndarray, k: int) -> List[int]:
    """Indices of the ``k`` largest entries of ``row``, best first.

    Uses ``argpartition`` to avoid sorting the whole row, then sorts only the
    ``k`` survivors.
    """
    k = min(k, row.shape[0])
    part = np.argpartition(row, -k)[-k:]
    return part[np.argsort(-row[part])].tolist()


# =============================================================================
# 6. Evaluation dictionaries
# =============================================================================


def load_dictionary(
    path: str,
    src: WordVectors,
    trg: WordVectors,
    encoding: str = "utf-8",
) -> Tuple[Dict[int, Set[int]], float]:
    """Read a gold dictionary and convert it to row indices.

    Expects one ``"<source> <target>"`` pair per line (the MUSE and VecMap
    format). Lines with more than two fields keep only the first two.

    Returns ``(gold, coverage)`` where ``gold`` maps a source index to the set
    of acceptable target indices, and ``coverage`` is the fraction of distinct
    source words whose pair survived the vocabulary lookup. Low coverage means
    the loaded vocabularies are too small for the test set to be meaningful.
    """
    gold: Dict[int, Set[int]] = collections.defaultdict(set)
    found: Set[str] = set()
    missing: Set[str] = set()

    with open(path, encoding=encoding, errors="surrogateescape") as handle:
        for line in handle:
            fields = line.split()
            if len(fields) < 2:
                continue
            src_word, trg_word = fields[0], fields[1]
            src_idx, trg_idx = src.index(src_word), trg.index(trg_word)
            if src_idx is None or trg_idx is None:
                missing.add(src_word)
            else:
                gold[src_idx].add(trg_idx)
                found.add(src_word)

    # A word is only missing if *none* of its translations were resolvable.
    missing -= found
    total = len(found) + len(missing)
    coverage = len(found) / total if total else 0.0
    return dict(gold), coverage


# =============================================================================
# 7. High-level entry point
# =============================================================================


def align(
    src: WordVectors,
    trg: WordVectors,
    src_lang: str = "src",
    trg_lang: str = "trg",
    **kwargs,
) -> Alignment:
    """Align two embedding spaces. One-call wrapper over
    :class:`GromovWassersteinAligner`.

    Any keyword accepted by :class:`GromovWassersteinAligner` may be passed
    through -- ``anchor_vocab``, ``entreg``, ``maxiter``, ``normalize_vecs`` and
    so on.

    Example
    -------
    ::

        src = WordVectors.load("wiki.en.vec", max_vocab=200_000)
        trg = WordVectors.load("wiki.es.vec", max_vocab=200_000)
        alignment = align(src, trg, "en", "es", anchor_vocab=2000)
    """
    return GromovWassersteinAligner(**kwargs).fit(src, trg, src_lang, trg_lang)


# =============================================================================
# 8. Command line interface
# =============================================================================


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Unsupervised bilingual lexicon induction with Gromov-Wasserstein.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    data = parser.add_argument_group("data")
    data.add_argument("--src-vectors", required=True, help="source embedding file")
    data.add_argument("--trg-vectors", required=True, help="target embedding file")
    data.add_argument("--src-lang", default="src", help="source language code")
    data.add_argument("--trg-lang", default="trg", help="target language code")
    data.add_argument("--dictionary", help="gold dictionary for evaluation (optional)")
    data.add_argument("--max-vocab", type=int, default=200_000,
                      help="vectors to load per language")
    data.add_argument("--encoding", default="utf-8")
    data.add_argument("--outdir", help="directory for projected vectors and arrays")

    gw = parser.add_argument_group("Gromov-Wasserstein")
    gw.add_argument("--anchor-vocab", type=int, default=2000,
                    help="words per language in the GW problem (cost is quadratic)")
    gw.add_argument("--metric", default="cosine",
                    choices=["cosine", "euclidean", "sqeuclidean"])
    gw.add_argument("--normalize-vecs", default="both",
                    choices=["both", "mean", "unit", "whiten", "whiten_zca", "none"])
    gw.add_argument("--normalize-dists", default="mean",
                    choices=["mean", "max", "median", "none"])
    gw.add_argument("--loss", default=SQUARE_LOSS, choices=[SQUARE_LOSS, KL_LOSS])
    gw.add_argument("--entreg", type=float, default=5e-4,
                    help="entropic regularization")
    gw.add_argument("--tol", type=float, default=1e-9, help="outer stopping tolerance")
    gw.add_argument("--maxiter", type=int, default=300, help="outer iterations")
    gw.add_argument("--distribs", default="uniform", choices=["uniform", "zipf"])
    gw.add_argument("--anchor-method", default="mutual_nn", choices=["mutual_nn", "all"])
    gw.add_argument("--max-anchors", type=int, default=None)

    ev = parser.add_argument_group("retrieval and evaluation")
    ev.add_argument("--score-type", default="projected",
                    choices=["projected", "coupling", "barycentric"])
    ev.add_argument("--adjust", default="csls", choices=["csls", "none"])
    ev.add_argument("--retrieval-vocab", type=int, default=50_000,
                    help="candidate pool size for full-vocabulary retrieval")
    ev.add_argument("--log-every", type=int, default=10)
    ev.add_argument("--quiet", action="store_true")
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    """Run the full pipeline from the command line.

    ::

        python otalign.py --src-vectors wiki.en.vec --trg-vectors wiki.es.vec \\
            --src-lang en --trg-lang es --dictionary en-es.0-5000.txt \\
            --anchor-vocab 2000 --maxiter 300
    """
    args = _build_parser().parse_args(argv)
    verbose = not args.quiet

    if verbose:
        print(f"Loading {args.src_vectors} and {args.trg_vectors} "
              f"(up to {args.max_vocab} words each)...")
    src = WordVectors.load(args.src_vectors, args.max_vocab, args.encoding)
    trg = WordVectors.load(args.trg_vectors, args.max_vocab, args.encoding)
    if verbose:
        print(f"  source: {src}\n  target: {trg}")

    alignment = align(
        src,
        trg,
        args.src_lang,
        args.trg_lang,
        anchor_vocab=args.anchor_vocab,
        metric=args.metric,
        normalize_vecs=args.normalize_vecs,
        normalize_dists=args.normalize_dists,
        loss=args.loss,
        entreg=args.entreg,
        tol=args.tol,
        maxiter=args.maxiter,
        distribs=args.distribs,
        anchor_method=args.anchor_method,
        max_anchors=args.max_anchors,
        verbose=verbose,
        log_every=args.log_every,
    )
    alignment.score_type = args.score_type
    alignment.adjust = None if args.adjust == "none" else args.adjust

    if args.dictionary:
        gold, coverage = load_dictionary(args.dictionary, alignment.src, alignment.trg)
        print(f"\nGold dictionary: {len(gold)} source words, "
              f"{coverage:.2%} vocabulary coverage.")
        # Report every scoring route, as the original script did, so the effect
        # of the coupling / mapping / CSLS choices is visible side by side.
        for score_type in ("coupling", "barycentric", "projected"):
            for adjust in (None, "csls"):
                label = score_type + ("+csls" if adjust else "")
                n_trg = (
                    args.retrieval_vocab if score_type == "projected"
                    else alignment.n_anchor_trg
                )
                try:
                    precisions = alignment.precision_at_k(
                        gold, score_type=score_type, adjust=adjust, n_trg=n_trg
                    )
                except ValueError as exc:
                    print(f"  {label:22s} skipped ({exc})")
                    continue
                print("  {:22s} ".format(label)
                      + "  ".join("P@{}: {:6.2%}".format(k, v)
                                  for k, v in precisions.items()))

    if args.outdir:
        if verbose:
            print(f"\nWriting projected vectors and arrays to {args.outdir}...")
        alignment.export(args.outdir)

    return 0


if __name__ == "__main__":
    sys.exit(main())
